[package]
name = "hts-sys"
version = "1.10.2"
authors = ["Christopher Schröder <christopher.schroeder@tu-dortmund.de>", "Johannes Köster <johannes.koester@tu-dortmund.de>"]
build = "build.rs"
links = "hts"
description = "This library provides HTSlib bindings."
readme = "README.md"
keywords = ["htslib", "bam", "bioinformatics", "pileup", "sequencing"]
license = "MIT"
repository = "https://github.com/samtools/htslib.git"
documentation = "https://docs.rs/rust-htslib"
edition = "2018"

[package.metadata.release]
pre-release-commit-message = "release version {{version}}"
tag-message = "Version {{version}} of Rust-HTSlib."

[dependencies]
#libc = "0.2.68"
libz-sys = { version = "1.0.25", features = ["static"] }
# https://github.com/alexcrichton/bzip2-rs/issues/56
bzip2-sys = { version = "0.1.8", optional = true }
# https://github.com/alexcrichton/xz2-rs/issues/62
lzma-sys = { version = "0.1.15", optional = true, features = ["static"], git = "https://github.com/brainstorm/xz2-rs", branch = "static_feature_flag" }
curl-sys = { version = "0.4.31+curl-7.70.0", optional = true, features = ["static-curl", "static-ssl"] }
#openssl-sys = { version = "0.9.56", optional = true, vendored = true}

[features]
default = ["bzip2", "lzma"]
bzip2 = ["bzip2-sys"]
lzma = ["lzma-sys"]
#openssl = ["openssl-sys"]
curl = ["curl-sys"]
static = []

[build-dependencies]
fs-utils = "1.1"
bindgen = { version = "0.53.1", default-features = false, features = ["runtime"] }
cc = "1.0"
glob = "0.3.0"
