on:
  push:
    branches:
      - master

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release_sys
        with:
          release-type: rust
          package-name: hts-sys
          bump-minor-pre-major: Yes
          monorepo-tags: true
          path: hts-sys

      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release_main
        with:
          release-type: rust
          package-name: rust-htslib
          bump-minor-pre-major: Yes
          monorepo-tags: true

      - uses: actions/checkout@v2
        if: ${{ steps.release_main.outputs.release_created || steps.release_sys.outputs.release_created }}

      - name: Install stable toolchain
        if: ${{ steps.release_main.outputs.release_created || steps.release_sys.outputs.release_created }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install system dependencies
        if: ${{ steps.release_main.outputs.release_created || steps.release_sys.outputs.release_created }}
        run: |
            sudo apt-get install --yes zlib1g-dev libbz2-dev musl musl-dev musl-tools clang libc6-dev

      - uses: Swatinem/rust-cache@v1.3.0
        if: ${{ steps.release_main.outputs.release_created || steps.release_sys.outputs.release_created }}

      - uses: katyo/publish-crates@v1
        if: ${{ steps.release_main.outputs.release_created || steps.release_sys.outputs.release_created }}
        with:
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}